navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 0.0
    
    magnetic_declination_radians: -0.0175
    zero_altitude: true
    
    publish_filtered_gps: true
    broadcast_cartesian_transform: false
    
    use_odometry_yaw: false
    wait_for_datum: false
    
    base_link_frame: base_link
    gps_frame: gps          # ‚Üê Changed from gps_link
    world_frame: odom